language: ruby
rvm:
- 2.1.5
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake
before_script:
- cp config/database.yml.travis config/database.yml
- cp config/secrets.yml.travis config/secrets.yml
- psql -c 'create database flashcards_test' -U postgres
