default:
  aws_access_key_id: 'qwertyuiopasdfghjklz'     # required
  aws_secret_access_key: 'qwertyuiopasdfghjklzqwertyuiopasdfghjklz' # required
  region: 'us-east-1'          # optional, defaults to 'us-east-1'
  